export const k12LeadershipOverrides: Record<string, Partial<Record<string, string>>> = {
  "CALSA Board Members::Riverside USD": {
    "Sup": "Sonia Llamas, Ed.D.",
    "CBO": "Erin Power",
    "Board 1": "Mr. Brent Lee",
    "Board 2": "Dr. Noemi Hernandez Alexander (Prof.)",
    "Board 3": "Dr. Jesse Tweed",
    "Board 4": "Mr. Dale Kinnear",
    "Board 5": "Ms. Amanda Vickers",
  },
  "CALSA Board Members::San Mateo-Foster City SD": {
    "Sup": "Diego R. Ochoa",
    "CBO": "Patrick Gaffney",
    "Board 1": "LaTisa Brooks",
    "Board 2": "Maggie Trinh",
    "Board 3": "Gene Kim",
    "Board 4": "Alison Proctor",
    "Board 5": "Stacy Ho",
  },
  "CALSA Board Members::Berryessa Union SD": {
    "Sup": "Dr. Roxane Fuentes",
    "CBO": "Kevin Franklin",
    "Board 1": "THELMA BOAC",
    "Board 2": "HUGO JIMENEZ",
    "Board 3": "KHOA NGUYEN",
    "Board 4": "JAI SRINIVASAN",
    "Board 5": "Jaria Jaug",
  },
  "CALSA Board Members::Woodland USD": {
    "Sup": "Elodia Ortega-Lampkin",
    "CBO": "Lewis Wiley, Jr.",
    "Board 1": "Deborah bautista zavala",
    "Board 2": "noel rodriguez",
    "Board 3": "laura brubaker",
    "Board 4": "bibiana garcia",
    "Board 5": "Kandice richardson fowler",
    "Board 6": "claudia rodriguez-mojica",
    "Board 7": "Rogelio villagrana",
  },
  "CALSA Board Members::Cutler-Orosi JUSD": {
    "Sup": "Yolanda Valdez",
    "CBO": "Faith Coleman",
    "Board 1": "Sandra Williams",
    "Board 2": "Marisol Rubalcaba",
    "Board 3": "Delia Martinez",
    "Board 4": "Mary Helen Espino",
    "Board 5": "Javier Quevedo",
    "Board 6": "Joni Jordan",
    "Board 7": "Karen Gonzalez",
  },
  "CALSA Board Members::Salinas City ESD": {
    "Sup": "Rebeca Andrade, Ed.D.",
    "CBO": "Nikki Herring",
    "Board 1": "Jessica Powell",
    "Board 2": "Belia Garcia",
    "Board 3": "Art Galimba",
    "Board 4": "Amy Ish",
    "Board 5": "Jennifer Zanzot",
  },
  "CALSA Board Members::Salinas UHSD": {
    "Sup": "Dr. Teresa López Alonzo",
    "CBO": "Ana Aguillon",
    "Board 1": "Vanessa M. Robinson",
    "Board 2": "Mitchell Huerta",
    "Board 3": "Nathalia Carrillo",
    "Board 4": "Jorge Rojas",
    "Board 5": "Tracy Filice",
    "Board 6": "Monica Lujan",
    "Board 7": "Michael Urquides",
  },
  "CALSA Board Members::Adelanto ESD": {
    "Sup": "Dr. Terry T. Walker",
    "CBO": "Zach Klemish",
    "Board 1": "Miguel Soto Jr.",
    "Board 2": "Stephanie Webster",
    "Board 3": "La Shawn Love-French",
    "Board 4": "Christina Steward",
    "Board 5": "Michael Krause",
  },
  "CLSBA Board Members::Oak Grove SD": {
    "Sup": "Dr. Ivan Chaidez",
    "CBO": "Mark E. Evans",
    "Board 1": "Nancy Yue",
    "Board 2": "Frances Herbert",
    "Board 3": "Otila Salazar Torres",
    "Board 4": "Diego Martinez",
    "Board 5": "Kaushik C. Joglekar",
  },
  "CLSBA Board Members::Woodland JUSD": {
    "Sup": "Elodia Ortega-Lampkin",
    "CBO": "Lewis Wiley",
    "Board 1": "Deborah bautista zavala",
    "Board 2": "noel rodriguez",
    "Board 3": "laura brubaker",
    "Board 4": "bibiana garcia",
    "Board 5": "Kandice richardson fowler",
    "Board 6": "claudia rodriguez-mojica",
    "Board 7": "Rogelio villagrana",
  },
  "CLSBA Board Members::San José USD": {
    "Sup": "Nancy Albarrán",
    "CBO": "Seth Reddy",
    "Board 1": "Teresa Castellanos",
    "Board 2": "Jose Magaña",
    "Board 3": "Carla Collins",
    "Board 4": "Brian Wheatley",
    "Board 5": "Nicole Gribstad",
  },
  "CLSBA Board Members::Hacienda La Puente USD": {
    "Sup": "Manoj Roychowdhury",
    "CBO": "Manoj Roychowdhury",
    "Board 1": "Stephanie Serrano",
    "Board 2": "Gino Kwok, Esq.",
    "Board 3": "Adriana Quinones",
    "Board 4": "Nancy Loera",
    "Board 5": "Jeffrey De La Torre",
  },
  "CLSBA Board Members::Monterey Peninsula USD": {
    "Sup": "Daniel “PK” Diffenbaugh",
    "CBO": "Ryan Altemeyer",
    "Board 1": "Maiaika Velazquez",
    "Board 2": "Veronica Miramontes",
    "Board 3": "Dr. Bettye Lusk",
    "Board 4": "Tom W. Jennings",
    "Board 5": "Amanda Whitmire",
    "Board 6": "Jeff Uchida",
    "Board 7": "Sarah Ofstedal",
  },
  "CLSBA Board Members::Tustin USD": {
    "Sup": "Mark Johnson, Ed.D",
    "CBO": "Harold Sullins",
    "Board 1": "Jonathan Stone",
    "Board 2": "Lynn Davis",
    "Board 3": "Jonathan Abelove",
    "Board 4": "Kathy Copeland",
    "Board 5": "Allyson Muñiz Damikolas",
  },
  "CLSBA Board Members::Sunnyvale SD": {
    "Sup": "Michael Gallagher",
    "CBO": "Arthur Cuffy",
    "Board 1": "Bridget Watson",
    "Board 2": "Peggy Shen Brewster",
    "Board 3": "Michelle Maginot",
    "Board 4": "Evelyn Castillo Profeta",
    "Board 5": "Isabel Jubes-Flamerich",
  },
  "CLSBA Board Members::Morgan Hill USD": {
    "Sup": "Dr. Carmen García",
    "CBO": "Kolvira Chheng",
    "Board 1": "John Horner",
    "Board 2": "Veronica Andrade",
    "Board 3": "Sarah Northrup Gadus",
    "Board 4": "Jennifer Marquez",
    "Board 5": "Nancy Altman",
    "Board 6": "Pamela Gardiner",
    "Board 7": "Rebecca Munson",
  },
  "CLSBA Board Members::Berkeley USD": {
    "Sup": "Enikia Ford Morthel",
    "CBO": "Pauline Follansbee",
    "Board 1": "Ka’Dijah Brown",
    "Board 2": "Mike Chang",
    "Board 3": "Jennifer Corn",
    "Board 4": "Jennifer Shanoski",
    "Board 5": "Ana Vasudeo",
  },
  "CLSBA Board Members::ABC Unified": {
    "Sup": "Dr. Gina Zietlow",
    "CBO": "Toan Nguyen",
    "Board 1": "Ernie Nishii",
    "Board 2": "Francisco Noyola",
    "Board 3": "Tatiana Yokoyama Bui",
    "Board 4": "Jean M. McHatton",
    "Board 5": "Leticia Mendoza",
    "Board 6": "Dr. Olga Rios",
    "Board 7": "Soo Yoo",
  },
  "Los Angeles County::Long Beach USD": {
    "Sup": "Dr. Jill Baker",
    "CBO": "Yumi Takahashi",
    "Board 1": "Diana Craighead",
    "Board 2": "Douglas Otto",
    "Board 3": "Isabel Lopez",
    "Board 4": "Erik Miller",
    "Board 5": "Juan Benitez",
  },
  "Los Angeles County::Pasadena USD": {
    "Sup": "Dr. Elizabeth J. Blanco",
    "CBO": "Saman Bravo-Karimi",
    "Board 1": "Jennifer Hall Lee",
    "Board 2": "Tina Fredricks",
    "Board 3": "Yarma Velázquez",
    "Board 4": "Kimberly Kenne",
    "Board 5": "Michelle Bailey",
    "Board 6": "Scott Harden",
    "Board 7": "Patrice McKenzie",
  },
  "Los Angeles County::Burbank USD": {
    "Sup": "Dr. John Paramo",
    "CBO": "Andrew Cantwell",
    "Board 1": "Armond Aghakhanian",
    "Board 2": "Laurette Cano",
    "Board 3": "Abby Pontzer Kamkar",
    "Board 4": "Emily Weisberg",
    "Board 5": "Charlene Tabet",
  },
  "Los Angeles County::Compton USD": {
    "Sup": "Dr. Darin Brawley",
    "CBO": "Dr. Shannon Soto",
    "Board 1": "Micah Ali",
    "Board 2": "Satra D. Zurita",
    "Board 3": "Alma Pleasant",
    "Board 4": "Ayanna Davis",
    "Board 5": "Sandra Moss",
    "Board 6": "Michael Hooper",
    "Board 7": "Denzell Perry",
  },
  "Los Angeles County::Pomona USD": {
    "Sup": "Darren Knowles",
    "CBO": "Sandra Garcia",
    "Board 1": "Roberta A. Perlman",
    "Board 2": "Tamara Gonzalez",
    "Board 3": "Arturo Jimenez",
    "Board 4": "Lisa Nashua",
    "Board 5": "Patricia Tye",
  },
  "Los Angeles County::Antelope Valley JUSHD": {
    "Sup": "Gregory Nehen",
    "CBO": "Kevin Vensko",
    "Board 1": "Carla Corona",
    "Board 2": "Miguel Sanchez IV",
    "Board 3": "Cynthia R.Hernandez",
    "Board 4": "Charles Hughes",
    "Board 5": "L. Rosemary Mann",
  },
  "Los Angeles County::Santa Monica-Malibu USD": {
    "Sup": "Dr. Antonio Shelton",
    "CBO": "Melody Canady",
    "Board 1": "Jon Kean",
    "Board 2": "Maria Leon-Vazquez",
    "Board 3": "Laurie Lieberman",
    "Board 4": "Alicia Mignano",
    "Board 5": "Stacey Rouse",
    "Board 6": "Jennifer Smith",
    "Board 7": "Richard Jesswein",
  },
  "Los Angeles County::Downey USD": {
    "Sup": "Dr. John A. Garcia, Jr.",
    "CBO": "Dr. Robert McEntire",
    "Board 1": "Tyrone Conde",
    "Board 2": "Mark Morris",
    "Board 3": "Giovanna Perez-Saab",
    "Board 4": "Jose J. Rodriguez",
    "Board 5": "Barbara Samperi",
    "Board 6": "Nancy A. Swenson",
    "Board 7": "Linda Saldaña",
  },
  "Los Angeles County::Arcadia USD": {
    "Sup": "David Vannasdall",
    "CBO": "Dierk Esseln",
    "Board 1": "Raymond Cheung",
    "Board 2": "Leigh Chavez",
    "Board 3": "Fenton Eng",
    "Board 4": "Shirley Yee",
    "Board 5": "Jennifer Vargo",
  },
  "Los Angeles County::PV Peninsula USD": {
    "Sup": "Dr. Devin Serrano",
    "CBO": "Brenna Terrones",
    "Board 1": "Linda Kurt",
    "Board 2": "Sara Deen",
    "Board 3": "Julie Hamill",
    "Board 4": "Ami Gandhi",
    "Board 5": "Eric Alegria",
  },
  "Los Angeles County::Redondo Beach USD": {
    "Sup": "Dr. Nikki Wesley",
    "CBO": "Dr. Annette Alpern",
    "Board 1": "Raymur Flinn",
    "Board 2": "Dan Elder",
    "Board 3": "Byung Cho",
    "Board 4": "Rolf Strutzenberg",
    "Board 5": "Rachel Silverman Nemeth",
  },
  "Los Angeles County::Culver City USD": {
    "Sup": "Dr. Alfonso Jimenez",
    "CBO": "Santha Rajiv",
    "Board 1": "Triston Ezidore",
    "Board 2": "Stephanie Loredo",
    "Board 3": "Brian Guerrero",
    "Board 4": "Andrew Lachman",
    "Board 5": "Lindsay Carlson",
  },
  "Los Angeles County::Manhattan Beach USD": {
    "Sup": "Dr. John Bowes",
    "CBO": "Dawnalyn Murakawa-Leopard",
    "Board 1": "Wysh Weinstein",
    "Board 2": "Tina Shivpuri",
    "Board 3": "Jen Dohner",
    "Board 4": "Jen Fenton",
    "Board 5": "Cathy Graves",
  },
  "Los Angeles County::San Marino USD": {
    "Sup": "Dr. Linda de la Torre",
    "CBO": "Dr. Stephen Choi",
    "Board 1": "Joseph Chang",
    "Board 2": "Francisco Gill",
    "Board 3": "Shelley Ryan",
    "Board 4": "Joanna Lam",
    "Board 5": "Joshua Snug",
  },
  "Los Angeles County::Paramount USD": {
    "Sup": "Dr. Joshua Lightle",
    "CBO": "Patricia Tu",
    "Board 1": "Alicia Anderson",
    "Board 2": "Sonia De Leon",
    "Board 3": "Eddie Cruz",
    "Board 4": "Yesenia Cuarenta",
    "Board 5": "Diane J. Martinez",
  },
  "Los Angeles County::Saugus Union SD": {
    "Sup": "Dr. Colleen Hawkins",
    "CBO": "Nick Heinlein",
    "Board 1": "Patti Garibay",
    "Board 2": "Anna Griese",
    "Board 3": "Katherine Cooper",
    "Board 4": "Christopher Trunkey",
    "Board 5": "Matthew Watson",
  },
  "Los Angeles County::San Gabriel USD": {
    "Sup": "James \"Jim\" Symonds",
    "CBO": "Lawrence Ferchaw",
    "Board 1": "Rochelle Kate Haas",
    "Board 2": "Cheryl A. Shellhart",
    "Board 3": "Gina Chi",
    "Board 4": "Robert Mercado",
    "Board 5": "Gary Thomas Scott",
  },
  "Los Angeles County::Fullerton JUHSD": {
    "Sup": "Steve McLaughlin",
    "CBO": "Ruben Hernandez",
    "Board 1": "Vicki Calhoun",
    "Board 2": "Marilyn Buchi",
    "Board 3": "Lauren Klatzker",
    "Board 4": "Joanne Fawley",
    "Board 5": "Chester Jeng",
  },
  "Los Angeles County::El Monte City SD": {
    "Sup": "Dr. Maribel Garcia",
    "CBO": "José Marcelino Herrera",
    "Board 1": "Elizabeth Rivas",
    "Board 2": "Cesar Peralta",
    "Board 3": "David Siegrist",
    "Board 4": "Jennifer Cobian",
    "Board 5": "Lisette Mendez Garcia",
  },
  "Los Angeles County::Lancaster Elementary SD": {
    "Sup": "Dr. Paul Marietti",
    "CBO": "Larry Freise",
    "Board 1": "Pamela Starlson",
    "Board 2": "Greg Tepe",
    "Board 3": "Keith Giles",
    "Board 4": "Julie Eutsler",
    "Board 5": "Duane Winn",
  },
  "Los Angeles County::Norwalk La Mirada USD": {
    "Sup": "Dr. Natasha Baker",
    "CBO": "Estuardo Santillan",
    "Board 1": "Narcis Brasov",
    "Board 2": "Rob Cancio",
    "Board 3": "Esperanza Free",
    "Board 4": "Norma Amezcua",
    "Board 5": "Jose M. Rios",
    "Board 6": "Lorena Vidauree",
    "Board 7": "Becky Langenwalter",
  },
  "Los Angeles County::Lynwood USD": {
    "Sup": "Gudiel R. Crosthwaite",
    "CBO": "Dr. Gretchen Janson",
    "Board 1": "Julian Del Real-Calleros",
    "Board 2": "Dr. Gary Hardie, Jr.",
    "Board 3": "Alfonso Morales",
    "Board 4": "Alma Carina Castro",
    "Board 5": "Maria G. Lopez",
  },
  "Los Angeles County::East Whittier CSD": {
    "Sup": "Dr. Marc Patterson",
    "CBO": "Marianne Sarrail",
    "Board 1": "Linda Small",
    "Board 2": "Jennifer De Baca Sandoval",
    "Board 3": "Richard Hever",
    "Board 4": "Elizabeth Leon",
    "Board 5": "Caro Jauregui",
  },
  "Los Angeles County::Los Nietos SD": {
    "Sup": "Ramiro Rubalcaba",
    "CBO": "Douglas McMasters",
    "Board 1": "Evelyn Avdalyan",
    "Board 2": "Maritza Nieves",
    "Board 3": "Emilio Sosa",
    "Board 4": "Catherine Martinez",
    "Board 5": "Edith Marcel",
  },
  "Los Angeles County::Alhambra USD": {
    "Sup": "Dr. Denise R. Jaramillo",
    "CBO": "Juanita Orta",
    "Board 1": "Fred L. Chang",
    "Board 2": "Kenneth Tang",
    "Board 3": "Marcia R. Wilson",
    "Board 4": "Robert L. Gin",
    "Board 5": "Kaysa Moreno",
  },
  "Orange County (K-12 District w/ +$100M Auth. Since 2020)::Anaheim UHSD": {
    "Sup": "Michael Matsuda",
    "CBO": "Dr. Nancy C. Nien",
    "Board 1": "Brian O'Neal",
    "Board 2": "Jessica Guerrero",
    "Board 3": "Annemarie Randle-Trejo",
    "Board 4": "Ron Hoshi",
    "Board 5": "Katherine H. Smith",
  },
  "Orange County (K-12 District w/ +$100M Auth. Since 2020)::Santa Ana USD": {
    "Sup": "Dr. Lorraine M. Perez",
    "CBO": "Ron Hacker",
    "Board 1": "Hector Bustos",
    "Board 2": "Katelyn Brazer Aceves",
    "Board 3": "Valerie Magdaleno",
    "Board 4": "Dr. Alfonso Alvarez",
    "Board 5": "Brenda Lebsack",
  },
  "Orange County (K-12 District w/ +$100M Auth. Since 2020)::Fullerton JUHSD": {
    "Sup": "Dr. Steve McLaughlin",
    "CBO": "Ruben Hernandez",
    "Board 1": "Dr. Vicki Calhoun",
    "Board 2": "Marilyn Buchi",
    "Board 3": "Lauren Klatzker",
    "Board 4": "Joanne Fawley",
    "Board 5": "Chester Jeng",
  },
  "Orange County (K-12 District w/ +$100M Auth. Since 2020)::Tustin USD": {
    "Sup": "Dr. Mark Johnson",
    "CBO": "Harold Sullins",
    "Board 1": "Jonathan Stone",
    "Board 2": "Lynn Davis",
    "Board 3": "Jonathan Abelove",
    "Board 4": "Dr. Kathy Copeland",
    "Board 5": "Allyson Muñiz Damikolas",
  },
  "Orange County (K-12 District w/ +$100M Auth. Since 2020)::Fullerton SD": {
    "Sup": "Dr. Robert “Bob” Pletka",
    "CBO": "Dr. Robert R. Coghlan",
    "Board 1": "Beverly Berryman",
    "Board 2": "Ruthi Hanchett",
    "Board 3": "Aaruni Thakur",
    "Board 4": "James Cho",
    "Board 5": "Vanesa Estrella",
  },
  "Orange County (K-12 District w/ +$100M Auth. Since 2020)::Brea Olinda USD": {
    "Sup": "Brinda C. Leon",
    "CBO": "Rick Champion",
    "Board 1": "Carrie Flanders",
    "Board 2": "Dr. Chris Becerra",
    "Board 3": "Joseph Covey",
    "Board 4": "Deana Miller",
    "Board 5": "Paul Ruiz",
  },
  "Riverside County (K-12 District w/ +$100M Auth. Since 2020)::Desert Sands USD": {
    "Sup": "Dr. Kelly May-Vollmar",
    "CBO": "Jordan Aquino",
    "Board 1": "Kailee Watson",
    "Board 2": "Michael Duran",
    "Board 3": "Humberto Alvarez",
    "Board 4": "Tricia Pearce",
    "Board 5": "Linda Porras",
  },
  "Riverside County (K-12 District w/ +$100M Auth. Since 2020)::Jurupa USD": {
    "Sup": "Dr. Trenton Hansen",
    "CBO": "Paula Ford",
    "Board 1": "Melissa Ragole",
    "Board 2": "Pamela Blynn",
    "Board 3": "Karen Bradford",
    "Board 4": "Raquel Ortiz Cornejo",
    "Board 5": "Jenny Felix",
  },
  "Riverside County (K-12 District w/ +$100M Auth. Since 2020)::Lake Elsinore USD": {
    "Sup": "Dr. Ryan Lewis",
    "CBO": "James Judziewicz",
    "Board 1": "Heidi Matthies Dodd",
    "Board 2": "April Purkiss",
    "Board 3": "Jill Leonard",
    "Board 4": "Mike Pacheco",
    "Board 5": "Juan I. Saucedo",
  },
  "Riverside County (K-12 District w/ +$100M Auth. Since 2020)::Moreno Valley USD": {
    "Sup": "Dr. Alejandro Ruvalcaba",
    "CBO": "Susana Lopez",
    "Board 1": "Sammie Luna",
    "Board 2": "Brandy Clark",
    "Board 3": "Johanna Levia",
    "Board 4": "Cleveland “CJ” Johnson",
    "Board 5": "Rhodes Williams",
  },
  "Riverside County (K-12 District w/ +$100M Auth. Since 2020)::Palm Springs USD": {
    "Sup": "Dr. Marcus Funchess",
    "CBO": "Jeffrey Simmons",
    "Board 1": "Sergio Espericueta",
    "Board 2": "Madonna Gerrell",
    "Board 3": "Karen Cornett",
    "Board 4": "John Gerardi",
    "Board 5": "Charlie E. Ervin Jr",
  },
  "Riverside County (K-12 District w/ +$100M Auth. Since 2020)::Val Verde USD": {
    "Sup": "Dr. Gordon Amerson",
    "CBO": "Garrick Owen",
    "Board 1": "Marla Kirkland",
    "Board 2": "Erika L. Zamora",
    "Board 3": "Daniel Aquino",
    "Board 4": "Dolores Holmes",
    "Board 5": "Melinda Young",
  },
  "Riverside County (K-12 District w/ +$100M Auth. Since 2020)::Alvord USD": {
    "Sup": "Dr. Reggie Thompkins",
    "CBO": "Alisha Underwood",
    "Board 1": "Georgina Ramirez",
    "Board 2": "Julie A. Moreno",
    "Board 3": "Carolyn M. Wilson",
    "Board 4": "Norma O. Berrellez",
    "Board 5": "Amanda Vasquez",
  },
  "Riverside County (K-12 District w/ +$100M Auth. Since 2020)::Menifee Union SD": {
    "Sup": "Dr. Jennifer Root",
    "CBO": "Marc Bommarito",
    "Board 1": "J. Kyle Root",
    "Board 2": "Jackie Johansen",
    "Board 3": "Xavier Padilla",
    "Board 4": "Morgan Singleton II",
    "Board 5": "Robert O’Donnell",
  },
  "San Bernadino County (K-12 District w/ +$100M Auth. Since 2020)::Redlands USD": {
    "Sup": "Juan Cabral",
    "CBO": "Jason Hill",
    "Board 1": "Michele Rendler",
    "Board 2": "Patty Holohan",
    "Board 3": "Jeannette Wilson",
    "Board 4": "Melissa Ayala-Quintero",
    "Board 5": "Candy Olson",
  },
  "San Bernadino County (K-12 District w/ +$100M Auth. Since 2020)::Fontana USD": {
    "Sup": "Miki R. Inbody",
    "CBO": "Leslie Barnes, Ed.D.",
    "Board 1": "Adam Perez",
    "Board 2": "Danielle Holley",
    "Board 3": "Angel Ramirez",
    "Board 4": "Mary Sandoval",
    "Board 5": "Marcelino Serna \"Mars\"",
  },
  "San Bernadino County (K-12 District w/ +$100M Auth. Since 2020)::Colton Joint USD": {
    "Sup": "Dr. Frank Miranda",
    "CBO": "Gregory Fromm",
    "Board 1": "Dan Flores",
    "Board 2": "Bertha Flores",
    "Board 3": "Israel Fuentes",
    "Board 4": "Patt Haro",
    "Board 5": "Frank A. Ibarra",
    "Board 6": "Berenice Sandoval",
    "Board 7": "Joanne E. Thoring-Ojeda",
  },
  "San Bernadino County (K-12 District w/ +$100M Auth. Since 2020)::Victor Valley Union HSD": {
    "Sup": "Carl J. Coles",
    "CBO": "Shawntée Milton",
    "Board 1": "Jose Berrios",
    "Board 2": "Rosalio Hinojos",
    "Board 3": "Kent Crosby",
    "Board 4": "Penny Edmiston",
    "Board 5": "Ken Larson",
  },
  "San Bernadino County (K-12 District w/ +$100M Auth. Since 2020)::Rialto USD": {
    "Sup": "Dr. Judy D. White",
    "CBO": "Diane Romo",
    "Board 1": "Dr. Stephanie E. Lewis",
    "Board 2": "Joseph W. Martinez",
    "Board 3": "Edgar Montes",
    "Board 4": "Evelyn P. Dominguez",
    "Board 5": "Dakira R. Williams",
  },
  "San Diego County (K-12 District w/ +$100M Auth. Since 2020)::San Diego USD": {
    "Sup": "Dr. Fabiola Bagula",
    "CBO": "Drew Rowlands",
    "Board 1": "Sabrina Bazzo",
    "Board 2": "Shana Hazan",
    "Board 3": "Cody Petterson",
    "Board 4": "Richard Barrera",
    "Board 5": "Sharon Whitehurst-Payne",
  },
  "San Diego County (K-12 District w/ +$100M Auth. Since 2020)::San Marcos USD": {
    "Sup": "Dr. Andy Johnsen",
    "CBO": "Erin Garcia",
    "Board 1": "Sarah Ahmad",
    "Board 2": "Andrés Martín",
    "Board 3": "Stacy Carlson",
    "Board 4": "Heidi Herrick",
    "Board 5": "Lena Meum",
  },
  "San Diego County (K-12 District w/ +$100M Auth. Since 2020)::Oceanside USD": {
    "Sup": "Dr. Julie A. Vitale",
    "CBO": "Dr. Todd McAteer",
    "Board 1": "Raquel Alvarez",
    "Board 2": "Stacy Begin",
    "Board 3": "Mike Blessing",
    "Board 4": "Eleanor Evans",
    "Board 5": "Nancy Licona",
  },
  "San Diego County (K-12 District w/ +$100M Auth. Since 2020)::Chula Vista ESD": {
    "Sup": "Dr. Eduardo Reyes",
    "CBO": "Mark Pong",
    "Board 1": "Lucy Ugarte",
    "Board 2": "Jessica R. Tolston",
    "Board 3": "Francisco Tamayo",
    "Board 4": "Keren Ramirez Dominguez",
    "Board 5": "Delia Dominguez Cervantes",
  },
  "San Diego County (K-12 District w/ +$100M Auth. Since 2020)::Encinitas Union SD": {
    "Sup": "Dr. Andrée Grey",
    "CBO": "Joseph Dougherty",
    "Board 1": "Emily Andrade",
    "Board 2": "Monica Lee",
    "Board 3": "Marla Strich",
    "Board 4": "Marlon Taylor",
    "Board 5": "Tom Morton",
  },
  "San Diego County (K-12 District w/ +$100M Auth. Since 2020)::La Mesa–Spring Valley SD": {
    "Sup": "David Feliciano",
    "CBO": "Tina Douglas",
    "Board 1": "Sarah Reed",
    "Board 2": "Rebecca McRae",
    "Board 3": "Brianna Coston",
    "Board 4": "Nathaniel Allen",
    "Board 5": "Minerva Martinez Scott",
  },
  "San Diego County (K-12 District w/ +$100M Auth. Since 2020)::Sweetwater Union HSD": {
    "Sup": "Dr. Moisés G. Aguirre",
    "CBO": "Dr. Jenny Salkeld",
    "Board 1": "Arturo Solis",
    "Board 2": "Dr. Adrián Arancibia",
    "Board 3": "ELVA LOPEZ-ZEPEDA",
    "Board 4": "Rudy Lopez",
    "Board 5": "Marti Emerald",
  },
  "City of Ontario Overlapping K-12 Districts::Chaffey JUHSD": {
    "Sup": "Mathew Holton",
    "CBO": "Rick Wiersma",
    "Board 1": "Dr. Donald E. English",
    "Board 2": "Arthur R. Bustamonte",
    "Board 3": "Cary W. Willborn",
    "Board 4": "Susan G. Ovitt",
    "Board 5": "Gilbert M. Zendejas",
    "Board 6": "Aamirah Day",
  },
  "City of Ontario Overlapping K-12 Districts::Chino Valley USD": {
    "Sup": "Norm Enfield, Ed.D.",
    "CBO": "Sandra H. Chen",
    "Board 1": "Sonja Shaw",
    "Board 2": "Vacated",
    "Board 3": "Andrew Cruz",
    "Board 4": "John Cervantes",
    "Board 5": "James Na",
  },
};
